name: Github CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Cancels previous runs of the same workflow
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ocaml: 4.14.x
          - os: ubuntu-latest
            ocaml: 4.13.x
          - os: ubuntu-latest
            ocaml: 4.12.x
          - os: ubuntu-latest
            ocaml: 4.11.x
          - os: ubuntu-latest
            ocaml: 5.0.x
          - os: macos-latest
            ocaml: 4.14.x
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 🐫 Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml }}
          dune-cache: true

      - name: 🐫🐪🐫 Get dependencies
        run: opam exec -- make opam-deps

      - name: 🧱 Build coq-lsp
        run: opam exec -- make build

  build-nix:
    name: Nix
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: ❄️ Setup Nix
        uses: cachix/install-nix-action@v18

      - name: 🧱 Build coq-lsp
        run: nix build

  client-compile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./editor/code
    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v3
      - name: 🚀 Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npx --yes vsce ls

  treefmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: ❄️ Setup Nix
        uses: cachix/install-nix-action@v18
      - name: 📐 Format with alejandra, ocamlformat, prettier
        run: nix fmt
